In [ ]:
https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy/blob/master/3.%20NumPy%20exercises.ipynb

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.25.1


In [7]:
np.zeros(10, dtype='i8')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [11]:
np.ones([2, 2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [14]:
X = np.ones([3, 2], dtype=np.float16)

In [17]:
np.ones(X.shape, dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [19]:
X = np.arange(4, dtype=np.int8)

np.ones_like(X)

array([1, 1, 1, 1], dtype=int8)

In [20]:
np.zeros_like(X)

array([0, 0, 0, 0], dtype=int8)

In [22]:
np.ones([4, 4], dtype=np.int8) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [24]:
np.ones_like(X) * 7

array([7, 7, 7, 7], dtype=int8)

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.randint(10, size=3)

array([9, 8, 8])

In [39]:
np.random.randn(3, 3, 3)

array([[[ 0.82559679, -0.72997666, -0.23436521],
        [ 1.13423034,  1.31265138,  0.23128849],
        [-1.79747166, -0.01064063,  0.77136648]],

       [[-0.84823919,  0.62758013, -0.52612296],
        [-0.43964431, -1.16727092, -0.45912166],
        [ 0.69837591,  0.45897303,  1.45808961]],

       [[-0.10362131,  1.01253697, -0.89928312],
        [-1.1660099 , -0.04769585,  0.13718937],
        [-0.00256969,  0.33066983,  1.94689632]]])

In [45]:
X = [1, 2, 3, 4]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


In [53]:
X = np.array([1, 2, 3, 4])
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[1 2 3 4] 140697162029872
[1 2 3 4] 140697161058608


In [54]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

In [60]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [63]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
Z = np.zeros((10, 10), dtype=np.int8)
print(Z)
print("%d bytes" % (Z.size * Z.itemsize))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
100 bytes


In [75]:
print(Z.itemsize)

1


In [82]:
X = np.array((1, 2, 3, 4))
print(X[0])
print(X[-1])
print(X[1:-1])

1
4
[2 3]


In [89]:
X[::-1]

array([4, 3, 2, 1])

In [92]:
X[::2]

array([1, 3])

In [112]:
X = np.arange(1, 17).reshape(4, 4)
print(X)

X[0]
X[-2]
X[0, 0] # X[0][0]
X[1:-1, 1:-1]
X[:2, :2]
X[2:, 2:]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[11, 12],
       [15, 16]])

In [127]:
X = [-5, -3, 0, 10, 40]

np.array(X, dtype=np.float32)



array([-5., -3.,  0., 10., 40.], dtype=float32)

In [130]:
X = [0, 10, -5, 40, -3]

X.sort()
X[4] = 1
X

[-5, -3, 0, 10, 1]

In [143]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(X[0].shape)
X[-1] = np.ones(X[0].shape)
X

(4,)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [146]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1, -1] = 0
X += 5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20,  5]])

In [150]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [153]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X > X.mean()
mask
X[mask]

array([ 2,  5,  6, 10])

In [156]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [160]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()
X.any()
X.sum()
X.mean()

0.9

In [169]:
X = np.arange(1, 17).reshape(4, 4)
X.sum(axis=0)
X.mean(axis=1)
X.max()

16

In [180]:
np.empty((2, 2))

array([[1., 0.],
       [0., 1.]])

In [174]:
np.eye(2, 2)

array([[1., 0.],
       [0., 1.]])